# Generated by Django 3.0 on 2020-11-07 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(blank=True, default='image_default/default.jpg', null=True, upload_to='images/', verbose_name='تصویر')),
                ('first_name', models.CharField(max_length=200, verbose_name='نام')),
                ('last_name', models.CharField(max_length=200, verbose_name='نام خانوادگی')),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': 'نام',
                'verbose_name_plural': 'اسامی',
                'ordering': ('first_name', 'last_name'),
            },
        ),
        migrations.CreateModel(
            name='NumberPhone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PhoneNumber', models.CharField(max_length=12, verbose_name='شماره تلفن')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name_number_phone', to='phonebook.Name', verbose_name='name')),
            ],
            options={
                'verbose_name': 'شماره',
                'verbose_name_plural': 'شماره ها',
            },
        ),
    ]
