# Generated by Django 3.0 on 2020-11-07 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phonebook', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Name',
            new_name='Contacts',
        ),
        migrations.RemoveField(
            model_name='numberphone',
            name='name',
        ),
        migrations.AddField(
            model_name='numberphone',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contact_number', to='phonebook.Contacts', verbose_name='مخاطبان'),
        ),
    ]
